services:
    # https://github.com/rectorphp/rector/issues/1024
    Rector\Rector\Typehint\ParentTypehintedArgumentRector:
        PHPUnit\Framework\TestCase:
            __construct:
                dataName: '' # no type

    Rector\PHPUnit\Rector\MethodCall\SpecificAssertContainsRector: ~
    Rector\PHPUnit\Rector\MethodCall\SpecificAssertInternalTypeRector: ~

    Rector\Rector\Class_\ClassReplacerRector:
        # https://github.com/sebastianbergmann/phpunit/issues/3123
        'PHPUnit_Framework_MockObject_MockObject': 'PHPUnit\Framework\MockObject\MockObject'
    Rector\PHPUnit\Rector\MethodCall\AssertEqualsParameterToSpecificMethodsTypeRector: ~

    Rector\Rector\Annotation\AnnotationReplacerRector:
        PHPUnit\Framework\TestCase:
            scenario: 'test'

    Rector\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        PHPUnit\Framework\TestCase:
            setUpBeforeClass: 'void'
            setUp: 'void'
            assertPreConditions: 'void'
            assertPostConditions: 'void'
            tearDown: 'void'
            tearDownAfterClass: 'void'
            onNotSuccessfulTest: 'void'
