<?php

namespace CompanyA;

class Foo
{
    public function foo()
    {
        $formula = [
        ]; // A fine comment sir
        $context = "foo";

        /** @var null|string $definition */
        $definition = null;

        // Some random comment here
        $engine = null;
    }

    public function bar(
    ) {
        /** @var null|string $definition */
        $definition = null;
    }
}
