# see: https://gnugat.github.io/2015/09/23/phpunit-with-phpspec.html
services:
    # 1. first convert method mocks
    Rector\PhpSpecToPHPUnit\Rector\MethodCall\PhpSpecMocksToPHPUnitMocksRector: ~
    # 2. then the class itself
    Rector\PhpSpecToPHPUnit\Rector\Class_\PhpSpecClassToPHPUnitClassRector: ~

    Rector\PhpSpecToPHPUnit\Rector\RenameSpecFileToTestFileRector: ~
