language: php

matrix:
  include:
    - php: 7.1
      env: STATIC_ANALYSIS=true RUN_RECTOR=true MONOREPO_SPLIT=true
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - phpenv config-rm xdebug.ini

script:
  # demo steps
  - bin/rector process demo/src/Controller --dry-run
  - bin/rector process demo/src/Form --dry-run
  - bin/rector process demo/tests --level phpunit60 --dry-run
  - bin/rector process demo/config --level symfony30 --dry-run

  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
      composer check-cs
      composer phpstan
    fi
  # Rector demo run
  - |
    if [[ $RUN_RECTOR == true ]]; then
      bin/rector process src tests --level symfony40 --dry-run
      bin/rector generate-rector-overview >> rector-overview.md
    fi

after_script:
  # split monorepo to packages - only on merge to master + publish prefixed version
  - |
    if [[ $TRAVIS_EVENT_TYPE == "push" && $MONOREPO_SPLIT == true && $TRAVIS_BRANCH == "master" ]]; then
        vendor/bin/monorepo-builder split -v
        composer rector-prefixed
    fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: never
