os: linux

dist: bionic

language: php

before_install:
    # Turn off XDebug
    - phpenv config-rm xdebug.ini

jobs:
    include:
        # Inspired by https://github.com/phpstan/phpstan-src/blob/088b9fab470632cea07f08a936fb0923a59b2ecb/.travis.yml#L47-L59
        # Deploy to https://github.com/rectorphp/rector-prefixed
        - name: Compile and Release rector.phar
          if: (branch = master OR tag IS present) && type = push
          php: 7.2
          script: |
              (
                  cd compiler/
                  composer install --no-interaction --no-suggest
                  travis_retry php bin/compile
                  php ../tmp/rector.phar
              )
              # Reuse tmp/rector.phar from previous run
              git clone --quiet "https://${GITHUB_TOKEN}@github.com/rectorphp/rector-prefixed.git" rector-prefixed
              cp tmp/rector.phar rector-prefixed/rector.phar
              cp tmp/rector.phar rector-prefixed/rector
              (
                  cd rector-prefixed/
                  git config user.name "TomasVotruba"
                  git config user.email "tomas.vot@gmail.com"
                  git add rector rector.phar

                  COMMIT_MSG="Updated Rector to commit ${TRAVIS_COMMIT}"
                  if [ -n "${TRAVIS_TAG}" ]; then COMMIT_MSG="Rector ${TRAVIS_TAG}"; fi
                  git commit -m "${COMMIT_MSG}"
                  git push --quiet --force origin master

                  if [ -n "${TRAVIS_TAG}" ]; then git tag "${TRAVIS_TAG}" && git push --quiet origin; fi
              )

notifications:
    email: false
