# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

dist: bionic

php: 7.4

before_install:
    - phpenv config-rm xdebug.ini

jobs:
    include:
        -
            name: "Split Monorepo"
            if: (branch = master OR tag IS present) && type = push
            script:
                - composer update
                # travis_retry to prevent fails
                - travis_retry vendor/bin/monorepo-builder split --ansi

notifications:
    email: false
