services:
    # https://github.com/symfony/symfony/pull/28447
    Rector\Rector\New_\NewToStaticCallRector:
        Symfony\Component\HttpFoundation\Cookie: ['Symfony\Component\HttpFoundation\Cookie', 'create']

    Rector\Rector\Class_\RenameClassRector:
        # https://github.com/symfony/symfony/commit/a7e319d9e1316e2e18843f8ce15b67a8693e5bf9
        Symfony\Bundle\FrameworkBundle\Controller\Controller: 'Symfony\Bundle\FrameworkBundle\Controller\AbstractController'
        # https://github.com/symfony/symfony/commit/744bf0e7ac3ecf240d0bf055cc58f881bb0b3ec0
        Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand: 'Symfony\Component\Console\Command\Command'
        Symfony\Component\Translation\TranslatorInterface: 'Symfony\Contracts\Translation\TranslatorInterface'

    # https://symfony.com/blog/new-in-symfony-4-2-important-deprecations
    Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector: ~
    Rector\Symfony\Rector\New_\RootNodeTreeBuilderRector: ~

    Rector\Rector\MethodCall\RenameMethodRector:
        Symfony\Component\Cache\CacheItem:
            getPreviousTags: 'getMetadata'
        Symfony\Component\Form\AbstractTypeExtension:
            getExtendedType: 'getExtendedTypes'

    Rector\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        Symfony\Component\Form\AbstractTypeExtension:
            getExtendedTypes: 'iterable'

    Rector\Rector\Visibility\ChangeMethodVisibilityRector:
        Symfony\Component\Form\AbstractTypeExtension:
            getExtendedTypes: 'static'

    Rector\Rector\ClassMethod\WrapReturnRector:
        Symfony\Component\Form\AbstractTypeExtension:
            getExtendedTypes: 'array'

    Rector\Rector\Argument\ArgumentDefaultValueReplacerRector:
        # https://github.com/symfony/symfony/commit/9493cfd5f2366dab19bbdde0d0291d0575454567
        Symfony\Component\HttpFoundation\Cookie:
            $secure:
                'false': null
            $samesite:
                'null': 'lax'

    Rector\Rector\Argument\ArgumentRemoverRector:
        # https://github.com/symfony/symfony/commit/f5c355e1ba399a1b3512367647d902148bdaf09f
        Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector:
            __construct:
                0: ~
                1: ~
