parameters:
    entity_repository_class: 'Rector\Tests\Rector\Architecture\DoctrineRepositoryAsService\Source\EntityRepositoryClass'
    entity_manager_class: 'Doctrine\ORM\EntityManager'

services:
    # order matters, this needs to be first to correctly detect parent repository
    Rector\Core\Rector\Architecture\RepositoryAsService\ReplaceParentRepositoryCallsByRepositoryPropertyRector: null
    Rector\Core\Rector\Architecture\RepositoryAsService\MoveRepositoryFromParentToConstructorRector: null
    Rector\Core\Rector\Architecture\RepositoryAsService\ServiceLocatorToDIRector: null
    Rector\Doctrine\Rector\Class_\RemoveRepositoryFromEntityAnnotationRector: null
