<?php

namespace Rector\Core\Tests\Rector\MethodCall\MethodCallToStaticCallRector\Fixture;

final class SomeClass
{
    private $anotherDependency;

    public function __construct(AnotherDependency $anotherDependency)
    {
        $this->anotherDependency = $anotherDependency;
    }

    public function loadConfiguration()
    {
        return $this->anotherDependency->process('value');
    }
}

?>
-----
<?php

namespace Rector\Core\Tests\Rector\MethodCall\MethodCallToStaticCallRector\Fixture;

final class SomeClass
{
    private $anotherDependency;

    public function __construct(AnotherDependency $anotherDependency)
    {
        $this->anotherDependency = $anotherDependency;
    }

    public function loadConfiguration()
    {
        return StaticCaller::anotherMethod('value');
    }
}

?>
