<?php

declare(strict_types=1);

use Rector\Renaming\Rector\MethodCall\RenameMethodRector;
use Rector\Renaming\Rector\Name\RenameClassRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

# https://www.php.net/manual/en/book.gmagick.php → https://www.php.net/manual/en/book.imagick.php
return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();

    $services->set(RenameClassRector::class)
        ->call('configure', [[
            RenameClassRector::OLD_TO_NEW_CLASSES => [
                'Gmagick' => 'Imagick',
                'GmagickPixel' => 'ImagickPixel',
            ],
        ]]);

    $services->set(RenameMethodRector::class)
        ->call('configure', [[
            RenameMethodRector::OLD_TO_NEW_METHODS_BY_CLASS => [
                'Gmagick' => [
                    'addimage' => 'addImage',
                    'addnoiseimage' => 'addNoiseImage',
                    'annotateimage' => 'annotateImage',
                    'blurimage' => 'blurImage',
                    'borderimage' => 'borderImage',
                    'charcoalimage' => 'charcoalImage',
                    'chopimage' => 'chopImage',
                    'commentimage' => 'commentImage',
                    'compositeimage' => 'compositeImage',
                    'cropimage' => 'cropImage',
                    'cropthumbnailimage' => 'cropThumbnailImage',
                    'cyclecolormapimage' => 'cycleColormapImage',
                    'deconstructimages' => 'deconstructImages',
                    'despeckleimage' => 'despeckleImage',
                    'drawimage' => 'drawImage',
                    'edgeimage' => 'edgeImage',
                    'embossimage' => 'embossImage',
                    'enhanceimage' => 'enhanceImage',
                    'equalizeimage' => 'equalizeImage',
                    'flipimage' => 'flipImage',
                    'flopimage' => 'flopImage',
                    'frameimage' => 'frameImage',
                    'gammaimage' => 'gammaImage',
                    'getcopyright' => 'getCopyright',
                    'getfilename' => 'getFilename',
                    'getimagebackgroundcolor' => 'getImageBackgroundColor',
                    'getimageblueprimary' => 'getImageBluePrimary',
                    'getimagebordercolor' => 'getImageBorderColor',
                    'getimagechanneldepth' => 'getImageChannelDepth',
                    'getimagecolors' => 'getImageColors',
                    'getimagecolorspace' => 'getImageColorspace',
                    'getimagecompose' => 'getImageCompose',
                    'getimagedelay' => 'getImageDelay',
                    'getimagedepth' => 'getImageDepth',
                    'getimagedispose' => 'getImageDispose',
                    'getimageextrema' => 'getImageExtrema',
                    'getimagefilename' => 'getImageFilename',
                    'getimageformat' => 'getImageFormat',
                    'getimagegamma' => 'getImageGamma',
                    'getimagegreenprimary' => 'getImageGreenPrimary',
                    'getimageheight' => 'getImageHeight',
                    'getimagehistogram' => 'getImageHistogram',
                    'getimageindex' => 'getImageIndex',
                    'getimageinterlacescheme' => 'getImageInterlaceScheme',
                    'getimageiterations' => 'getImageIterations',
                    'getimagematte' => 'getImageMatte',
                    'getimagemattecolor' => 'getImageMatteColor',
                    'getimageprofile' => 'getImageProfile',
                    'getimageredprimary' => 'getImageRedPrimary',
                    'getimagerenderingintent' => 'getImageRenderingIntent',
                    'getimageresolution' => 'getImageResolution',
                    'getimagescene' => 'getImageScene',
                    'getimagesignature' => 'getImageSignature',
                    'getimagetype' => 'getImageType',
                    'getimageunits' => 'getImageUnits',
                    'getimagewhitepoint' => 'getImageWhitePoint',
                    'getimagewidth' => 'getImageWidth',
                    'getpackagename' => 'getPackageName',
                    'getquantumdepth' => 'getQuantumDepth',
                    'getreleasedate' => 'getReleaseDate',
                    'getsamplingfactors' => 'getSamplingFactors',
                    'getsize' => 'getSize',
                    'getversion' => 'getVersion',
                    'hasnextimage' => 'hasNextImage',
                    'haspreviousimage' => 'hasPreviousImage',
                    'implodeimage' => 'implodeImage',
                    'labelimage' => 'labelImage',
                    'levelimage' => 'levelImage',
                    'magnifyimage' => 'magnifyImage',
                    'mapimage' => 'mapImage',
                    'medianfilterimage' => 'medianFilterImage',
                    'minifyimage' => 'minifyImage',
                    'modulateimage' => 'modulateImage',
                    'motionblurimage' => 'motionBlurImage',
                    'newimage' => 'newImage',
                    'nextimage' => 'nextImage',
                    'normalizeimage' => 'normalizeImage',
                    'oilpaintimage' => 'oilPaintImage',
                    'previousimage' => 'previousImage',
                    'profileimage' => 'profileImage',
                    'quantizeimage' => 'quantizeImage',
                    'quantizeimages' => 'quantizeImages',
                    'queryfontmetrics' => 'queryFontMetrics',
                    'queryfonts' => 'queryFonts',
                    'queryformats' => 'queryFormats',
                    'radialblurimage' => 'radialBlurImage',
                    'raiseimage' => 'raiseImage',
                    'readimage' => 'readimages',
                    'readimageblob' => 'readImageBlob',
                    'readimagefile' => 'readImageFile',
                    'reducenoiseimage' => 'reduceNoiseImage',
                    'removeimage' => 'removeImage',
                    'removeimageprofile' => 'removeImageProfile',
                    'resampleimage' => 'resampleImage',
                    'resizeimage' => 'resizeImage',
                    'rollimage' => 'rollImage',
                    'rotateimage' => 'rotateImage',
                    'scaleimage' => 'scaleImage',
                    'separateimagechannel' => 'separateImageChannel',
                    'setCompressionQuality' => 'getCompressionQuality',
                    'setfilename' => 'setFilename',
                    'setimagebackgroundcolor' => 'setImageBackgroundColor',
                    'setimageblueprimary' => 'setImageBluePrimary',
                    'setimagebordercolor' => 'setImageBorderColor',
                    'setimagechanneldepth' => 'setImageChannelDepth',
                    'setimagecolorspace' => 'setImageColorspace',
                    'setimagecompose' => 'setImageCompose',
                    'setimagedelay' => 'setImageDelay',
                    'setimagedepth' => 'setImageDepth',
                    'setimagedispose' => 'setImageDispose',
                    'setimagefilename' => 'setImageFilename',
                    'setimageformat' => 'setImageFormat',
                    'setimagegamma' => 'setImageGamma',
                    'setimagegreenprimary' => 'setImageGreenPrimary',
                    'setimageindex' => 'setImageIndex',
                    'setimageinterlacescheme' => 'setImageInterlaceScheme',
                    'setimageiterations' => 'setImageIterations',
                    'setimageprofile' => 'setImageProfile',
                    'setimageredprimary' => 'setImageRedPrimary',
                    'setimagerenderingintent' => 'setImageRenderingIntent',
                    'setimageresolution' => 'setImageResolution',
                    'setimagescene' => 'setImageScene',
                    'setimagetype' => 'setImageType',
                    'setimageunits' => 'setImageUnits',
                    'setimagewhitepoint' => 'setImageWhitePoint',
                    'setsamplingfactors' => 'setSamplingFactors',
                    'setsize' => 'setSize',
                    'shearimage' => 'shearImage',
                    'solarizeimage' => 'solarizeImage',
                    'spreadimage' => 'spreadImage',
                    'stripimage' => 'stripImage',
                    'swirlimage' => 'swirlImage',
                    'thumbnailimage' => 'thumbnailImage',
                    'trimimage' => 'trimImage',
                    'writeimage' => 'writeImage',
                ],
                'GmagickPixel' => [
                    'getcolor' => 'getColor',
                    'getcolorcount' => 'getColorCount',
                    'getcolorvalue' => 'getColorValue',
                    'setcolor' => 'setColor',
                    'setcolorvalue' => 'setColorValue',
                ],
            ],
        ]]);
};
