<?php declare(strict_types=1);

use Symfony\Component\Yaml\Yaml;

$yaml = [];

Symfony\Component\Yaml\Yaml::parse($yaml);

Symfony\Component\Yaml\Yaml::parse($yaml);

Symfony\Component\Yaml\Yaml::parse($yaml, Symfony\Component\Yaml\Yaml::PARSE_CONSTANT);

Yaml::parse($yaml);

Symfony\Component\Yaml\Yaml::parse($yaml);
Symfony\Component\Yaml\Yaml::parse($yaml, 56);
Symfony\Component\Yaml\Yaml::parse($yaml);
Symfony\Component\Yaml\Yaml::parse($yaml, 'hi');
Symfony\Component\Yaml\Yaml::parse($yaml);
