imports:
    - { resource: 'phpunit-exception.yaml' }

services:
    # ref. https://github.com/sebastianbergmann/phpunit/compare/5.7.9...6.0.0
    Rector\Rector\Namespace_\PseudoNamespaceToNamespaceRector:
        $namespacePrefixesWithExcludedClasses:
            PHPUnit_:
                # exclude this class, since it has no namespaced replacement
                - 'PHPUnit_Framework_MockObject_MockObject'

    Rector\PHPUnit\Rector\ClassMethod\AddDoesNotPerformAssertionToNonAssertingTestRector: null
    Rector\PHPUnit\Rector\MethodCall\GetMockBuilderGetMockToCreateMockRector: null
