services:
    Rector\PHPUnit\Rector\Class_\TestListenerToHooksRector: null
    Rector\PHPUnit\Rector\MethodCall\ExplicitPhpErrorApiRector: null
    Rector\PHPUnit\Rector\MethodCall\SpecificAssertContainsWithoutIdentityRector: null
