# source: https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html

services:
    Rector\Rector\Class_\RenameClassRector:
        Cake\Http\Client\CookieCollection: 'Cake\Http\Cookie\CookieCollection'
        Cake\Console\ShellDispatcher: 'Cake\Console\CommandRunner'

    Rector\Rector\MethodCall\RenameMethodRector:
        Cake\Database\Schema\TableSchema:
            column: 'getColumn'
            constraint: 'getConstraint'
            index: 'getIndex'

    Rector\CakePHP\Rector\MethodCall\ModalToGetSetRector:
        Cake\Cache\Cache:
            config: ~
            registry: ~
        Cake\Console\Shell:
            io: ~
        Cake\Console\ConsoleIo:
            outputAs: ~
        Cake\Console\ConsoleOutput:
            outputAs: ~
        Cake\Database\Connection:
            logger: ~
        Cake\Database\TypedResultInterface:
            returnType: ~
        Cake\Database\TypedResultTrait:
            returnType: ~
        Cake\Database\Log\LoggingStatement:
            logger: ~
        Cake\Datasource\ModelAwareTrait:
            modelType: ~
        Cake\Database\Query:
            valueBinder:
                get: 'getValueBinder'
                set: 'valueBinder'
        Cake\Database\Schema\TableSchema:
            columnType: ~
        Cake\Datasource\QueryTrait:
            eagerLoaded:
                get: 'isEagerLoaded'
                set: 'eagerLoaded'
        Cake\Event\EventDispatcherInterface:
            eventManager: ~
        Cake\Event\EventDispatcherTrait:
            eventManager: ~
        Cake\Error\Debugger:
            outputAs:
                get: 'getOutputFormat'
                set: 'setOutputFormat'
        Cake\Http\ServerRequest:
            env:
                get: 'getEnv'
                set: 'withEnv'
            charset:
                get: 'getCharset'
                set: 'withCharset'
        Cake\I18n\I18n:
            locale: ~
            translator: ~
            defaultLocale: ~
            defaultFormatter: ~
        Cake\ORM\Association\BelongsToMany:
            sort: ~
        Cake\ORM\LocatorAwareTrait:
            tableLocator: ~
        Cake\ORM\Table:
            validator: ~
        Cake\Routing\RouteBuilder:
            extensions: ~
            routeClass: ~
        Cake\Routing\RouteCollection:
            extensions: ~
        Cake\TestSuite\TestFixture:
            schema: ~
        Cake\Utility\Security:
            salt: ~
        Cake\View\View:
            template: ~
            layout: ~
            theme: ~
            templatePath: ~
            layoutPath: ~
            autoLayout:
                get: 'isAutoLayoutEnabled'
                set: 'enableAutoLayout'
