# https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers
# https://github.com/laravel/framework/pull/26898
imports:
    - { resource: 'static/array-str-functions-to-static-call.yaml'}

# see: https://laravel.com/docs/5.8/upgrade
services:
    Rector\Laravel\Rector\StaticCall\MinutesToSecondsInCacheRector: ~

    Rector\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        Illuminate\Contracts\Cache\Repository:
            put: 'bool'
            forever: 'bool'
        Illuminate\Contracts\Cache\Store:
            put: 'bool'
            putMany: 'bool'
            forever: 'bool'

    Rector\Rector\Property\RenamePropertyRector:
        Illuminate\Routing\UrlGenerator:
            cachedSchema: 'cachedScheme'
