imports:
    # from https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/helpers.php to direct static calls
    - { resource: 'static/array-str-functions-to-static-call.yaml'}

services:
    Rector\Laravel\Rector\StaticCall\FacadeStaticCallToConstructorInjectionRector: ~
    Rector\Laravel\Rector\StaticCall\RequestStaticValidateToInjectRector: ~

    Rector\Rector\FuncCall\FunctionToNewRector:
        collect: 'Illuminate\Support\Collection'

    Rector\Laravel\Rector\FuncCall\HelperFunctionToConstructorInjectionRector: ~
