# github action that checks code with Rector
name: Rector

on:
    pull_request: null

jobs:
    rector:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == '__CURRENT_REPOSITORY__'
        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v4
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   uses: "ramsey/composer-install@v3"

            -   run: vendor/bin/rector --ansi
            # @todo apply coding standard if used

            -
                # commit only to core contributors who have repository access
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: '[rector] Rector fixes'
                    commit_author: 'GitHub Action <actions@github.com>'
                    commit_user_email: 'action@github.com'
