name: Bare Run

on:
    pull_request: null
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0', '8.1']

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: php bin/rector --version --ansi

            -   run: php bin/rector list --ansi
