name: Build Scoped Rector

# builds the content of https://github.com/rectorphp/rector-prefixed
on:
    push:
        branches:
            - master

    release:
        types:
            - published

    # @todo remove after merge, this line is just for testing
    pull_request: null

jobs:
    build_scoped_rector:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    # this must be PHP 7.4, as phpstan-src requires it
                    php-version: 7.4
                    tools: composer:v2
                # fixes https://github.com/rectorphp/rector/pull/4559/checks?check_run_id=1359814403, see https://github.com/shivammathur/setup-php#composer-github-oauth
                env:
                    COMPOSER_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            # 1. prepare dependencies
            # replace phpstan.phar with phpstan-src, see https://github.com/phpstan/phpstan-src
            -   run: |
                    composer remove phpstan/phpstan --no-update
                    composer config repositories.repo-name vcs https://github.com/phpstan/phpstan-src.git

                    # @todo resolve specific last version somehow automated
                    composer require phpstan/phpstan-src:dev-master#3a08cb0 --no-update

                    # phpdocumentor/reflection-docblock 4.3.4 is blocker on PHP 8, so we have to ignore php version
                    composer require "phpdocumentor/reflection-docblock:dev-master#5.2 as 4.3.4" --no-update

                    # mimics PHPStan https://github.com/phpstan/phpstan-src/blob/3a08cb018572938ca6b90f861c5fbca17baeab4c/composer.json#L17
                    composer require jetbrains/phpstorm-stubs:dev-master#b2402e4a525593f68ff46303dcc6bc625437276a --no-update

            # phpdocumentor/reflection-docblock 4.3.4 is blocker on PHP 8, so we have to ignore php version
            -   run: composer update --no-progress --ansi --ignore-platform-req php

            # downgrade PHPStan code to PHP 7.2
            -   run: bin/rector process vendor/phpstan/phpstan-src/src --config ci/downgrade-phpstan-php74-rector.php --ansi

            # Avoid Composer v2 platform checks (composer.json requires PHP 7.4+, but below we are running 7.3)
            -   run: composer config platform-check false

#            -   run: mkdir nested-rector
            # @see https://unix.stackexchange.com/a/554912/74260
            # copy to nested directory, so we have clear plate to work with
            -   run: rsync -av * nested-rector

            # see https://github.com/humbug/php-scoper#without-box
            -   run: composer update --working-dir nested-rector --no-dev --prefer-dist --ansi

            # 2. scope it
            -   run: wget https://github.com/humbug/php-scoper/releases/download/0.13.9/php-scoper.phar
            -
                # to make paths in scoper.inc.php work, as the are relative
                run: cd nested-rector && php ../php-scoper.phar add-prefix bin config packages rules src templates vendor composer.json --output-dir ../rector-scoped --config scoper.inc.php --force --ansi -vvv


            -   run: composer dump-autoload --working-dir rector-scoped --ansi --optimize --classmap-authoritative

            # 2.5 scope composer.json
            -   run: vendor/bin/package-scoper scope-composer-json rector-scoped/composer.json --ansi

            -   run: rm rector-scoped/phpstan.neon

            # 3. run it
            -   run: chmod 777 rector-scoped/bin/rector

            # 4. get tag - see https://github.com/WyriHaximus/github-action-get-previous-tag
            #-
            #    id: previous_tag
            #    uses: "WyriHaximus/github-action-get-previous-tag@master"

            # 5. publish it to remote repository
            -
                # Uses an action in the root directory
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'rector-scoped'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: 'rector-prefixed'
                    # @todo put into standalone action with only tagging
                    # tag: ${{ steps.previous_tag.outputs.tag }}
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
