name: Check Services

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    check_services:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none # disable xdebug, pcov
            -   run: composer install --no-progress
            -   run: php ci/check_services_in_yaml_configs.php
