name: CI Review

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    ci_review:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Validate Monorepo"
                        write_run: "composer propagate --ansi"
                        commit_message: "propagate monorepo dependencies"
                        check_run: "composer validate-monorepo --ansi"

                    -
                        name: "Sync Doctrine Annotation Parser"
                        write_run: "bin/rector sync-annotation-parser --ansi"
                        commit_message: "sync doctrine/annotations parser"
                        check_run: "bin/rector sync-annotation-parser --dry-run --ansi"

                    -
                        name: "Sync Rector & Nodes Docs"
                        write_run: "composer docs"
                        commit_message: "Generate Rector & Nodes documentation"
                        check_run: "composer docs"

                    -
                        name: 'Apply Coding Standard'
                        write_run: "composer fix-cs"
                        commit_message: "Apply coding standards"
                        check_run: "composer check-cs"


        name: ${{ matrix.actions.name }}

        runs-on: ubuntu-latest

        steps:
            # workaround for missing secret in fork PRs - see https://github.com/actions/checkout/issues/298
            # see https://github.com/rectorphp/rector/commit/d395e1c28b8e6a56711dcc2e10490a82965850e4
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            # in forks, the token is not available - so we cannot us eit
            -
                if: github.event.pull_request.head.repo.full_name != github.repository
                uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v1

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.write_run }}

            # see https://github.com/rectorphp/rector/pull/4531/checks?check_run_id=1338642220#step:7:401 + https://stackoverflow.com/questions/62653114/how-to-deal-with-this-git-warning-pulling-without-specifying-how-to-reconcile#:~:text=warning%3A%20Pulling%20without%20specifying%20how,default%20strategy)%20git%20config%20pull.
            # see https://github.com/rlespinasse/github-slug-action
            -
                name: Inject slug/short variables
                uses: rlespinasse/github-slug-action@v3.x

            -   run: git branch --set-upstream-to=origin/${{ env.GITHUB_HEAD_REF_SLUG_URL }} ${{ env.GITHUB_REF_SLUG }}
            -   run: git pull --ff-only

            # see https://github.com/EndBug/add-and-commit
            -
                uses: EndBug/add-and-commit@v5.1.0
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: . --force
                    message: '[ci-review] ${{ matrix.actions.commit_message }}'
                    author_name: rector-bot
                    author_email: tomas@getrector.org
                    # solves https://github.com/rectorphp/rector/runs/1335693491#step:7:394
                    pull_strategy: '--rebase'
                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            -   run: ${{ matrix.actions.check_run }}
