name: Code Coverage

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: pcov
            -   run: composer install --no-progress --ansi
            -   run: |
                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
                    COVERALLS_PARALLEL: true
                    COVERALLS_FLAG_NAME: PHP 7.3
