name: drupal-metatag-without-console

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_with_drupal:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # Install Drupal
                    composer create-project drupal/recommended-project drupal --dev --no-progress

            -   run: |
                    # Install Rector, metatag (without console)
                    cd drupal
                    composer require drupal/metatag:1.12 palantirnet/drupal-rector

            -   run: |
                    # Run Rector on metatag/src/Generator
                    cd drupal
                    cp vendor/palantirnet/drupal-rector/rector.yml .
                    vendor/bin/rector process web/modules/contrib/metatag/src/Generator
