# This workflow runs system tests: Use the Rector application from the source
# checkout to process "fixture" projects in tests/system-tests
# to see if those can be processed successfully
name: End to End tests that expect diff

on:
    pull_request: null
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    end_to_end_with_diff:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0', '8.1']
                directory:
                    - 'e2e/attributes'
                    - 'e2e/container-configurator'

        name: End to end test with diff - ${{ matrix.directory }}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -
                run: composer install --ansi
                working-directory: ${{ matrix.directory }}

            -
                run: ../../bin/rector --ansi
                working-directory: ${{ matrix.directory }}
