name: Fatal Scan

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    fatal_scan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
            -   run: composer install --no-progress
            -   run: bin/rector scan-fatal-errors tests/Source/FatalErrors
