name: Static Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
            -   run: |
                    composer install --no-progress
                    composer require staabm/annotate-pull-request-from-checkstyle:^1.0
            # turn the phpstan errors (formatted in checkstyle-format) into github pull request check annotations
            -   run: composer phpstan -- --error-format=checkstyle | vendor/bin/cs2pr
