name: Build docker images
on:
    push:
        # Publish `master` as Docker `latest` image.
        branches:
            - master

        # Publish `v1.2.3` tags as releases.
        tags:
            - '*'

jobs:
    publish_images:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                php-version: ['7.3', '7.4', '8.0']
        steps:
            - uses: actions/checkout@v2

            - name: Log into container registries
              run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build images
              run: |
                  # Strip git ref prefix from version
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

                  # Strip "v" prefix from tag name
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

                  # Use Docker `latest` tag convention
                  [ "$VERSION" == "master" ] && VERSION=latest

                  docker buildx create --name builder-php${{ matrix.php-version }} --use
                  docker buildx build \
                        --progress plain \
                        --cache-from=rector/rector:build-cache-php${{ matrix.php-version }} \
                        --cache-to=type=registry,ref=rector/rector:build-cache-php${{ matrix.php-version }},mode=max,push=true \
                        --target rector \
                        --push \
                        --tag rector/rector:$VERSION-php${{ matrix.php-version }} \
                        --build-arg PHP_VERSION=${{ matrix.php-version }} .

                  # For master build create php version tag etc: rector/rector:php8.0
                  [ "$VERSION" == "latest" ] && docker tag rector/rector:$VERSION-php${{ matrix.php-version }} rector/rector:php${{ matrix.php-version }}

                  # For php 8.0 create ref tag etc: rector/rector:0.9.31
                  [ "${{ matrix.php-version }}" == "8.0" ] && docker tag rector/rector:$VERSION-php${{ matrix.php-version }} rector/rector:$VERSION

                  docker push rector/rector -a || true

            - name: Build Rector "secured"
              if: matrix.php-version == '8.0'
              run: |
                  docker buildx build \
                        --progress plain \
                        --cache-from=rector/rector:build-cache-php${{ matrix.php-version }} \
                        --target rector-secured \
                        --push \
                        --tag rector/rector:secured \
                        --build-arg PHP_VERSION=${{ matrix.php-version }} .
