name: Build docker images
on:
    push:
        # Publish `master` as Docker `latest` image.
        branches:
            - master

        # Publish `v1.2.3` tags as releases.
        tags:
            - '*'

jobs:
    publish_images:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                php-version: ['7.3', '7.4', '8.0']
        steps:
            - uses: actions/checkout@v2

            - name: Log into container registries
              run: |
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build images
              run: |
                  DOCKER_TAGS=""

                  # Pull tag and branch from github.ref, which is either refs/heads/... or refs/tags/...
                  TAG=$(echo "${{ github.ref }}" | sed -e '/refs\/tags\//!d; s,refs/.*/v\?\(.*\),\1,')
                  BRANCH=$(echo "${{ github.ref }}" | sed -e '/refs\/heads\//!d; s,refs/.*/\(.*\),\1,')

                  if [ "master" == "$BRANCH" ]; then
                      DOCKER_TAGS="$DOCKER_TAGS php${{ matrix.php-version }}"
                      if [ "8.0" == "${{ matrix.php-version }}" ]; then
                          DOCKER_TAGS="$DOCKER_TAGS latest"
                      fi
                  fi

                  if [ ! -z "$TAG" ]; then
                      DOCKER_TAGS="$DOCKER_TAGS $TAG-php${{ matrix.php-version }}"
                      if [ "8.0" ==  "${{ matrix.php-version }}" ]; then
                          DOCKER_TAGS="$DOCKER_TAGS $TAG"
                      fi
                  fi

                  echo "Image will be tagged with: $DOCKER_TAGS"

                  DOCKER_TAG_ARG=""
                  for ARG in $DOCKER_TAGS; do
                      DOCKER_TAG_ARG="$DOCKER_TAG_ARG --tag rector/rector:$ARG"
                  done

                  docker buildx create --name builder-php${{ matrix.php-version }} --use
                  docker buildx build \
                        --progress plain \
                        --cache-from=rector/rector:build-cache-php${{ matrix.php-version }} \
                        --cache-to=type=registry,ref=rector/rector:build-cache-php${{ matrix.php-version }},mode=max,push=true \
                        --target rector \
                        --push \
                        $DOCKER_TAG_ARG \
                        --build-arg PHP_VERSION=${{ matrix.php-version }} .
