name: Rector

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    rector:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: bin/rector process --config rector-ci.yaml --debug --dry-run
            -   run: bin/rector process --config rector-ci.yaml --debug --dry-run src
