name: Rector 0.7.2 and Drupal

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_with_drupal:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # 1. install locally
                    mkdir test-paths
                    cd test-paths

                    # Install Drupal with Rector 0.7.2
                    mkdir drupal-rector072
                    composer create-project drupal/recommended-project drupal-rector072 --dev --no-progress
                    cd drupal-rector072
                    composer require drupal/mailjet palantirnet/drupal-rector:dev-rector-0.7
                    cp vendor/palantirnet/drupal-rector/rector.yml .
                    vendor/bin/rector process web/modules/contrib/mailjet/lib/mailjet-api-php/src/mailjet.api.inc --dry-run -e
