name: Sync Annotation Parser

on:
    pull_request: null

jobs:
    sync_annotatoin_parser:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v1

            -   run: composer install --no-progress --ansi

            # write
            -   run: bin/rector sync-annotation-parser --ansi

            -
                uses: EndBug/add-and-commit@v5
                with:
                    add: 'packages'
                    message: '[ci-review] sync doctrine/annotations parser'
                env:
                    # to get push access
                    token: ${{ secrets.ACCESS_TOKEN }}

            -   run: bin/rector sync-annotation-parser --dry-run --ansi
