name: Test With Drupal

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_with_drupal:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   name: Install Drupal project
                run: |
                    # Install latest Drupal version
                    composer create-project drupal/recommended-project drupal
                    cd drupal

                    # use rector-prefixed v0.6.13
                    composer require rector/rector-prefixed:0.6.13 --dev

            -   run: bin/rector process web/core/modules/aggregator/src/Plugin/views/row/Rss.php --set deadcode --dry-run --config ci/config/rector-drupal.yaml

            -   run: |
                    # use rector-prefixed v0.7
                    composer require rector/rector-prefixed:0.7 --dev

            -   run: bin/rector process web/core/modules/aggregator/src/Plugin/views/row/Rss.php --set deadcode --dry-run --config ci/config/rector-drupal.yaml
